before:
  hooks:
    - go mod tidy

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

source:
  enabled: true

checksum: {}

sboms:
  - artifacts: source
