package goabnf

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// GenerateGoParser runs go/format on its output, so a nil error already proves
// the emitted source is syntactically valid Go. These checks pin that property
// across representative grammar shapes (repetition, ambiguity, recursion,
// multi-symbol productions) and the full ABNF meta-grammar, plus the presence of
// the expected public surface.
func Test_U_GenerateGoParser(t *testing.T) {
	cases := []struct{ src, root string }{
		{`a = *"a"` + "\r\n", "a"},
		{`a = 2*3("a" / "aa")` + "\r\n", "a"},
		{`a = 0*9999999999"x"` + "\r\n", "a"}, // huge bound: O(1) baked, no unroll
		{`a = a a / "a"` + "\r\n", "a"},       // ambiguous
		{`a = a / "a"` + "\r\n", "a"},         // infinitely ambiguous
		{`ip = 1*3DIGIT 3("." 1*3DIGIT)` + "\r\n", "ip"},
	}
	for _, c := range cases {
		g := mustGrammar(c.src)
		src, err := GenerateGoParser(g, c.root, "genp")
		require.NoErrorf(t, err, "generate %q", c.src)
		s := string(src)
		assert.Contains(t, s, "package genp")
		assert.Contains(t, s, "func Parse(input []byte) (*Result, error)")
		assert.Contains(t, s, "func (r *Result) NumTrees() *big.Int")
		assert.Containsf(t, s, "const gRootName = \""+c.root+"\"", "root marker for %q", c.src)
	}

	// The ABNF meta-grammar must generate cleanly too.
	src, err := GenerateGoParser(ABNF, "rulelist", "genp")
	require.NoError(t, err)
	assert.Greater(t, len(src), 1000)
	assert.True(t, strings.HasPrefix(string(src), "// Code generated by go-abnf"))
}

func Test_U_GenerateGoParser_UnknownRoot(t *testing.T) {
	g := mustGrammar("a = \"x\"\r\n")
	_, err := GenerateGoParser(g, "nonexistent", "genp")
	require.Error(t, err)
}

// genABNFMain is a tiny driver compiled alongside the generated parser. It reads
// a grammar file named on the command line and prints the parse outcome as
// "valid<TAB>numtrees<TAB>ambiguous".
const genABNFMain = `package main
 
import (
	"fmt"
	"os"
)
 
func main() {
	b, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Println("READERR", err)
		os.Exit(1)
	}
	r, err := Parse(b)
	if err != nil {
		fmt.Println("PARSEERR", err)
		os.Exit(1)
	}
	fmt.Printf("%v\t%s\t%v\n", r.Valid(), r.NumTrees().String(), r.Ambiguous())
}
`

// Test_F_GeneratedABNFParser_ParsesABNFGrammar is an end-to-end test of the code
// generator: it generates a parser for the ABNF meta-grammar, then compiles and
// runs that parser as a standalone program (via `go run`) inside a throwaway
// module, and feeds it the ABNF grammar from testdata/abnf.abnf (the RFC 5234 +
// errata self-definition). The generated parser must accept the grammar and must
// agree with the library oracle (ParseForest) on validity, tree count and
// ambiguity. A malformed grammar must be rejected, again in agreement.
//
// Isolation: everything the generated program needs (parser, driver, go.mod, and
// a copy of the grammar input) is written into t.TempDir() -- a fresh randomly
// named directory, outside the package tree, that the testing framework removes
// automatically on completion (including on failure/panic). Nothing is left
// behind and concurrent runs do not collide.
func Test_F_GeneratedABNFParser_ParsesABNFGrammar(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping functional codegen test in -short mode")
	}
	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skip("go toolchain not found in PATH; skipping functional codegen test")
	}

	grammarPath := filepath.Join("testdata", "abnf.abnf")
	grammar, err := os.ReadFile(grammarPath)
	if err != nil {
		t.Skipf("cannot read %s: %v", grammarPath, err)
	}

	// Generate a specialised parser for ABNF rooted at rulelist.
	src, err := GenerateGoParser(ABNF, "rulelist", "main")
	require.NoError(t, err, "generating ABNF parser")

	// Throwaway, isolated module in a random temp dir (auto-removed by t.Cleanup).
	dir := t.TempDir()
	mustWrite := func(name string, content []byte) {
		require.NoError(t, os.WriteFile(filepath.Join(dir, name), content, 0o644))
	}
	mustWrite("parser.go", src)
	mustWrite("main.go", []byte(genABNFMain))
	mustWrite("go.mod", []byte("module genabnf\n\ngo 1.18\n"))
	mustWrite("valid.abnf", grammar)
	// A malformed grammar (a rule with no defined-as) must be rejected.
	mustWrite("invalid.abnf", []byte("rule rulename\r\n"))

	run := func(inputFile string) string {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()
		cmd := exec.CommandContext(ctx, goBin, "run", ".", inputFile)
		cmd.Dir = dir
		out, err := cmd.CombinedOutput()
		require.NoErrorf(t, err, "go run . %s failed:\n%s", inputFile, out)
		return strings.TrimSpace(string(out))
	}

	oracle := func(input []byte) string {
		f, err := ParseForest(input, ABNF, "rulelist")
		require.NoError(t, err)
		return fmt.Sprintf("%v\t%s\t%v", f.Valid(), f.NumTrees().String(), f.Ambiguous())
	}

	// Positive: the generated parser parses testdata/abnf.abnf and agrees with
	// the library on validity, tree count and (un)ambiguity.
	{
		got := run("valid.abnf")
		want := oracle(grammar)
		assert.Equal(t, want, got, "generated parser must agree with the library on testdata/abnf.abnf")
		assert.Truef(t, strings.HasPrefix(got, "true\t"),
			"the ABNF grammar in testdata/abnf.abnf must parse as valid; got %q", got)
	}

	// Negative: a malformed grammar is rejected, and the generated parser again
	// agrees with the library.
	{
		got := run("invalid.abnf")
		want := oracle([]byte("rule rulename\r\n"))
		assert.Equal(t, want, got, "generated parser must agree with the library on a malformed grammar")
		assert.Truef(t, strings.HasPrefix(got, "false\t"),
			"a malformed grammar must be rejected; got %q", got)
	}
}
